name: Deploy Frontend

on:
  push:
    branches: [main, master]
    paths:
      - 'packages/frontend/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: packages/frontend/package-lock.json

      - name: Install dependencies
        working-directory: packages/frontend
        run: npm ci

      - name: Build
        working-directory: packages/frontend
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Deploy
        run: |
          echo "Configure deployment steps here"
          echo "Examples:"
          echo "- Deploy to Vercel (automatically detects Next.js)"
          echo "- Deploy to Netlify"
          echo "- Build and push Docker image"

